os: osx
language: node_js
node_js:
- '7'
branches:
  only:
    - master
deploy:
  provider: pages
  local_dir: ${TRAVIS_BUILD_DIR}
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
